// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

namespace Cards
{


	//this list will be used to store all the used cards and their status
	public class CardsList
	{

		public List<Card> list;

		public CardsList ()
		{
			list = new List<Card> ();
		}


		public void shuffleDeck(){
			System.Random rng = new System.Random ();
			int n = list.Count;
			while (n > 1) {
				n--;
				int k = rng.Next(n + 1);
				Card c = list[k];
				list[k] = list[n];
				list[n] = c;
			}
		}

		public Card removeCardAt(int a){
			Card ret = list [a];
			list.RemoveAt (a);

			return ret;
		}

		//each time a card is added, it should be added in the right list, so we don't really need to check their type
		//however, we need to check if the cards turn counts is lower or higher than the ones in the existing list
		//if it is lower, it should appear before them
		public void addCard(Card card){
			list.Add (card);
			list.Sort((x,y) => {return x.currentCount - y.currentCount;});

		}

		public void updateList(){

			int a = 0;

			foreach (Card c in list) {
				c.currentCount--;
				if(c.currentCount <=0)a++;
			}

			if (a > 0)
				list.RemoveRange (0, a);
		}

		public int getAttribute(bool damage = false, bool guard = false, bool move = false){
			int attribute = 0;

			foreach (Card c in list) {
				attribute += c.isDamageCard() && damage ? c.damage : (c.isGuardCard() && guard? c.guard : c.movement);
			}

			return attribute;
		}

		public Card popFirstCard(){

			return removeCardAt (0);
		}

		public void decreaseAttribute(int decrease, bool damage = false, bool guard = false, bool move = false){

			int b = 0;
			for(int a = 0; a < list.Count && decrease > 0; a++){
				decrease -= list[a].isDamageCard() && damage ? list[a].damage : (list[a].isGuardCard() && guard? list[a].guard : list[a].movement);
				b++;
			}
			if(b > 0)
				list.RemoveRange (0, b);
		}


		public int getCount(){
			return list.Count;
		}
	}
}

