// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using TBTK;

namespace Cards
{
	public class CardTransform : MonoBehaviour
	{
		public Card transformCard;

		void Start(){
			this.transformCard = (Card) transform.GetComponent<Card> ();
		}

		private void activateCard(CardsStackManager stack){
			if (this.transformCard.damageCard) 
				stack.addDamageCard(this.transformCard);
			if (this.transformCard.guardCard)
				stack.addGuardCard (this.transformCard);
			if (this.transformCard.moveCard)
				stack.addMoveCard (this.transformCard);

			GameControl.SelectUnit (GameControl.selectedUnit);

			//Do some sort of animation then destroy this card
			this.transform.SetParent (null);
			this.transform.position = CardsHandManager.getInstance ().cardsLimbo;
			CardsHandManager.getInstance ().cardsInDiscard.addCard (transformCard);
		}

		void OnMouseDown(){
			if (CardsHandManager.getInstance () != null && CardsHandManager.getInstance ().mode == CardsHandManager.modes._DeckBuild) {
				GameObject o = (GameObject) Resources.Load("Prefabs/Cards/" + this.transform.name);
				CardsHandManager.getInstance().instantiator.addPrefab(o);
			}
			else if (CardsHandManager.instance.selectedCard == this && GameControl.selectedUnit.factionID == FactionManager.GetPlayerFactionID()[0])
				activateCard ((CardsStackManager) GameControl.selectedUnit.GetComponent<CardsStackManager>());
			else 
				CardsHandManager.instance.selectedCard = this;
		}

	}
}

