// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;


namespace Cards
{
	public class CardsHandManager : MonoBehaviour
	{
		public static CardsHandManager instance;
		public int handSize;
		public Transform deck;

		public CardTransform selectedCard;

		public Transform cardPrefab;

		public CardsList cardsInDeck;

		public CardsList cardsInDiscard;

		void Awake ()
		{
			if (instance == null)
				instance = this;

			cardsInDeck = new CardsList ();
		}

		public static CardsHandManager getInstance(){
			return instance;
		}

		public void updateHand(){
			if (instance.transform.childCount < handSize) {
				for(int a = handSize - instance.transform.childCount; a != handSize; a++){
					Transform newCardT = (Transform) Instantiate(cardPrefab);
					Card pop = cardsInDeck.popFirstCard();
				}
			}
		}


	}
}

